### PR TITLE
Add a test for =pod Html

### PR DESCRIPTION
**Pull request by coke**
Issue #23

### CODE REVIEW

**Comment by coke** [comment]
Here's a very simplistic test, just making sure that no <p>'s were added to the code. (I expected that nothing would change, but this is a start)

**Comment by coke** [comment]
Branch now has a test and an update to not update html/xhtml sections at all. All tests (including the new one) pass

**Comment by coke** [comment]
I'm still not convinced this is 100% right, though.

**Comment by W4anD0eR96** [comment]
If all text inside =pod Html is raw HTML, it's right. Because Pod machinery wrap para into Pod::Block::Para.

However, users might using pod6 code inside Html block, which cause type object insert inside Html, like `C<code>` generate `Pod::FormattingCode<140289445450176> `. Thus I use `node2rawtext` instead, and now `C<code> -> code`. Anyway, do not using pod6 at all is recommended.

Remain the `unescape` in order to meet case when someone wants to write `C<>` or `B<>` literally for some reason. Although it results `&lt;` should be written as `&amp;lt;`, both of them are rare usage, possibility ahead convenience.

**Pull request closed without merging**
