### PR TITLE
Add a version

### PR DESCRIPTION
**Pull request by awwaiid**
I'm only doing a PR so that if someone knows better than me if this is a bad idea they might be able to stop me. I'll merge this soon otherwise.

### CODE REVIEW

**Comment by zoffixznet** [comment]
I'm by no means an expert, but shouldn't this change also modify [this line](https://github.com/perl6/Pod-To-HTML/blob/master/lib/Pod/To/HTML.pm#L1) to `unit class Pod::To::HTML:ver<0.0.1>` ?

**Comment by niner** [comment]
Not necessarily

**Comment by awwaiid** [comment]
Added! I guess assuming ci passes again I'll merge.

**Comment by zoffixznet** [comment]
Weird that adding the version makes that fail. I know that moving `use URI...` *above* `unit` would fix that though

**Comment by awwaiid** [comment]
Naw... I think it's an unrelated panda issue which makes it so you have to try every install twice :(

**Comment by zoffixznet** [comment]
Seems the version in METAfile has already been updated, making this PR obsolete. Closing.

**Pull request closed without merging**
